import { WebSocketServer, WebSocket } from 'ws';
import { v4 as uuidv4 } from 'uuid';
import { IncomingMessage } from 'http';
import { DGLabWSMessage, DGLabWSType } from './protocol';
import { EventEmitter } from 'events';

// ─── 事件总线：让 index.ts 监听 APP 反馈 ───
export const serverEvents = new EventEmitter();

// Maps a client's ID to their WebSocket connection
const clients = new Map<string, WebSocket>();
// Maps a client's ID to their bound partner's ID
const bindings = new Map<string, string>();
// Valid control-end IDs generated by /dg_qr
const validControlIds = new Set<string>();

// ─── 心跳 ───
const HEARTBEAT_INTERVAL_MS = 20_000; // 20s
let heartbeatTimer: NodeJS.Timeout | null = null;

/**
 * Generates a dynamic control ID that is authorized to be bound.
 */
export function generateControlId(): string {
  const id = `control-${uuidv4()}`;
  validControlIds.add(id);
  return id;
}

/**
 * Starts the DG-Lab WebSocket server.
 */
let wssInstance: WebSocketServer | null = null;

export function startDGLabServer(port: number) {
  const wss = new WebSocketServer({ port });
  wssInstance = wss;

  // ─── 心跳：定期向所有 client 发送 heartbeat ───
  heartbeatTimer = setInterval(() => {
    clients.forEach((ws, id) => {
      if (ws.readyState === WebSocket.OPEN) {
        const hb: DGLabWSMessage = {
          type: DGLabWSType.HEARTBEAT,
          clientId: id,
          targetId: '',
          message: 'heartbeat'
        };
        ws.send(JSON.stringify(hb));
      }
    });
  }, HEARTBEAT_INTERVAL_MS);

  wss.on('connection', (ws, req: IncomingMessage) => {
    const urlPath = (req.url || '').replace(/^\//, '');
    let assignedControlId: string | null = null;

    if (urlPath && validControlIds.has(urlPath)) {
      assignedControlId = urlPath;
    }

    const clientId = uuidv4();
    clients.set(clientId, ws);

    // Send the ID back to the client
    const bindMsg: DGLabWSMessage = {
      type: DGLabWSType.BIND,
      clientId: clientId,
      targetId: '',
      message: 'targetId'
    };
    ws.send(JSON.stringify(bindMsg));
    console.log(`[DG-Lab] Client connected: ${clientId}` +
      (assignedControlId ? ` (QR: ${assignedControlId})` : ''));

    // If connected via QR, auto-bind
    if (assignedControlId) {
      bindings.set(assignedControlId, clientId);
      bindings.set(clientId, assignedControlId);

      const successMsg: DGLabWSMessage = {
        type: DGLabWSType.BIND,
        clientId: assignedControlId,
        targetId: clientId,
        message: '200'
      };
      ws.send(JSON.stringify(successMsg));
      console.log(`[DG-Lab] Auto-bound App (${clientId}) <-> Control (${assignedControlId})`);
      serverEvents.emit('bind', { appId: clientId, controlId: assignedControlId });
    }

    ws.on('message', (data) => {
      handleMessage(data.toString(), clientId);
    });

    ws.on('close', () => {
      handleDisconnect(clientId);
    });
  });

  console.log(`[DG-Lab] WebSocket server started on port ${port}`);
}

function handleMessage(jsonData: string, senderClientId: string) {
  try {
    const msg: DGLabWSMessage = JSON.parse(jsonData);

    // ─── 心跳包直接忽略 ───
    if (msg.type === DGLabWSType.HEARTBEAT) {
      return;
    }

    // ─── 绑定请求 ───
    if (msg.type === DGLabWSType.BIND && msg.message === 'DGLAB' && msg.clientId && msg.targetId) {
      const controlEndId = msg.clientId;
      const appEndId = msg.targetId;

      if (!validControlIds.has(controlEndId)) {
        console.error(`[DG-Lab] Rejecting bind: invalid control ID ${controlEndId}`);
        return;
      }
      if (!clients.has(appEndId)) {
        console.error(`[DG-Lab] Rejecting bind: App ${appEndId} not connected`);
        return;
      }

      // 防止重复绑定
      if (bindings.has(controlEndId) && bindings.get(controlEndId) === appEndId) {
        console.log(`[DG-Lab] Already bound: ${controlEndId} <-> ${appEndId}, skipping`);
        return;
      }

      bindings.set(controlEndId, appEndId);
      bindings.set(appEndId, controlEndId);

      const successMsg: DGLabWSMessage = {
        type: DGLabWSType.BIND,
        clientId: controlEndId,
        targetId: appEndId,
        message: '200'
      };
      clients.get(appEndId)?.send(JSON.stringify(successMsg));
      console.log(`[DG-Lab] Bound App (${appEndId}) <-> Control (${controlEndId})`);
      serverEvents.emit('bind', { appId: appEndId, controlId: controlEndId });

    } else if (msg.type === DGLabWSType.MSG && msg.message) {
      // ─── APP 上报的强度反馈: strength-A强度+B强度+A上限+B上限 ───
      const strengthFeedback = msg.message.match(/^strength-(\d+)\+(\d+)\+(\d+)\+(\d+)$/);
      if (strengthFeedback) {
        serverEvents.emit('strength-feedback', {
          strengthA: parseInt(strengthFeedback[1]!),
          strengthB: parseInt(strengthFeedback[2]!),
          limitA: parseInt(strengthFeedback[3]!),
          limitB: parseInt(strengthFeedback[4]!),
        });
        // 仍然转发给绑定的控制端
      }

      // ─── APP 反馈按钮: feedback-X ───
      const feedbackMatch = msg.message.match(/^feedback-(\d)$/);
      if (feedbackMatch) {
        const index = parseInt(feedbackMatch[1]!);
        serverEvents.emit('feedback', { index });
        console.log(`[DG-Lab] APP feedback button pressed: index=${index}`);
      }

      // 转发给绑定的对端
      if (msg.targetId) {
        const recipient = clients.get(msg.targetId);
        recipient?.send(jsonData);
      }
    }
  } catch (error) {
    console.error('[DG-Lab] Failed to handle message:', error);
  }
}

export function stopDGLabServer(): Promise<void> {
  return new Promise((resolve) => {
    if (heartbeatTimer) {
      clearInterval(heartbeatTimer);
      heartbeatTimer = null;
    }
    if (wssInstance) {
      clients.forEach((ws) => { try { ws.close(); } catch (_) {} });
      clients.clear();
      bindings.clear();
      validControlIds.clear();
      wssInstance.close(() => {
        wssInstance = null;
        resolve();
      });
    } else {
      resolve();
    }
  });
}

/**
 * Send a command to all bound Apps.
 * Automatically checks message length limit (1950 chars).
 */
export function sendCommandToApps(commandStr: string) {
  bindings.forEach((partnerId, myId) => {
    if (validControlIds.has(myId)) {
      const ws = clients.get(partnerId);
      if (ws && ws.readyState === WebSocket.OPEN) {
        const msg: DGLabWSMessage = {
          type: DGLabWSType.MSG,
          clientId: myId,
          targetId: partnerId,
          message: commandStr
        };
        const json = JSON.stringify(msg);
        if (json.length > 1950) {
          console.warn(`[DG-Lab] Message too long (${json.length} > 1950), dropping`);
          return;
        }
        ws.send(json);
      }
    }
  });
}

function handleDisconnect(clientId: string) {
  clients.delete(clientId);
  const partnerId = bindings.get(clientId);
  if (partnerId) {
    bindings.delete(clientId);
    bindings.delete(partnerId);

    const partnerWs = clients.get(partnerId);
    const breakMsg: DGLabWSMessage = {
      type: DGLabWSType.BREAK,
      clientId: clientId,
      message: '209'
    };
    partnerWs?.send(JSON.stringify(breakMsg));
    console.log(`[DG-Lab] Client ${clientId} disconnected, notified partner ${partnerId}`);
    serverEvents.emit('disconnect', { clientId, partnerId });
  } else {
    console.log(`[DG-Lab] Client ${clientId} disconnected.`);
  }
}

/**
 * 获取当前连接状态
 */
export function getConnectionStatus(): { clients: number; bindings: number; controlIds: number } {
  return {
    clients: clients.size,
    bindings: bindings.size / 2,
    controlIds: validControlIds.size,
  };
}
